language: python

matrix:
  include:
  - python: "2.7"
    env: NUMPY_VERSION=1.7.1
  - python: "3.6"
    env: NUMPY_VERSION=1.12.1

dist: trusty

script: py.test

install: pip install numpy==$NUMPY_VERSION
